service: workspace-management

plugins:
  - serverless-appsync-plugin

layers:
  dependencies:
    path: layer
    description: Required dependencies for data processing
    compatibleRuntimes:
      - python3.9

provider:
  name: aws
  runtime: python3.9
  profile: ikonicshop
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - !GetAtt UserTable.Arn
            - !GetAtt AccountTable.Arn
            - !GetAtt WorkspaceTable.Arn
            - !GetAtt PathTable.Arn
            - !GetAtt ComponentTable.Arn
            - !GetAtt DataTable.Arn
            - !Sub "${UserTable.Arn}/index/*"
            - !Sub "${AccountTable.Arn}/index/*"
            - !Sub "${WorkspaceTable.Arn}/index/*"
            - !Sub "${PathTable.Arn}/index/*"
            - !Sub "${ComponentTable.Arn}/index/*"
            - !Sub "${DataTable.Arn}/index/*"
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
          Resource: !Sub "${DataBucket.Arn}/*"

custom:
  tablePrefix: ${self:service}-${self:provider.stage}
  tableName:
    user: ${self:custom.tablePrefix}-user
    account: ${self:custom.tablePrefix}-account
    workspace: ${self:custom.tablePrefix}-workspace
    path: ${self:custom.tablePrefix}-path
    component: ${self:custom.tablePrefix}-component
    data: ${self:custom.tablePrefix}-data

  # AppSync configuration
  appSync:
    name: ${self:service}-${self:provider.stage}
    authenticationType: API_KEY
    apiKeys:
      - name: default
        description: Default API Key
        expiresAfter: 30d
    schema:
      - schema/schema.graphql
      - schema/schema_additions.graphql
    mappingTemplatesLocation: schema/resolvers
    additionalAuthentication:
      - authenticationType: API_KEY
    defaultAuthentication:
      authenticationType: API_KEY
    substitutions:
      subscriptions: true
    mappingTemplates:
      - type: Query
        field: listWorkspaces
        dataSource: workspaceTable
        request: Query.listWorkspaces.req.vtl
        response: Query.listWorkspaces.res.vtl

      - type: Mutation
        field: bulkCreateData
        dataSource: bulkDataSource
        request: Mutation.bulkCreateData.req.vtl
        response: Mutation.bulkCreateData.res.vtl

      - type: Mutation
        field: createData
        dataSource: dataTable
        request: Mutation.createData.req.vtl
        response: Mutation.createData.res.vtl

      - type: Mutation
        field: deleteData
        dataSource: dataTable
        request: Mutation.deleteData.req.vtl
        response: Mutation.deleteData.res.vtl

      - type: Query
        field: listData
        dataSource: dataTable
        request: Query.listData.req.vtl
        response: Query.listData.res.vtl

      - type: Mutation
        field: createComponent
        dataSource: componentTable
        request: Mutation.createComponent.req.vtl
        response: Mutation.createComponent.res.vtl

      - type: Mutation
        field: deleteComponent
        dataSource: componentTable
        request: Mutation.deleteComponent.req.vtl
        response: Mutation.deleteComponent.res.vtl

    dataSources:
      - type: AMAZON_DYNAMODB
        name: workspaceTable
        config:
          tableName: ${self:custom.tableName.workspace}
          serviceRoleArn: !GetAtt AppSyncDynamoDBServiceRole.Arn

      - type: AMAZON_DYNAMODB
        name: pathTable
        config:
          tableName: ${self:custom.tableName.path}
          serviceRoleArn: !GetAtt AppSyncDynamoDBServiceRole.Arn

      - type: AMAZON_DYNAMODB
        name: componentTable
        config:
          tableName: ${self:custom.tableName.component}
          serviceRoleArn: !GetAtt AppSyncDynamoDBServiceRole.Arn

      - type: AMAZON_DYNAMODB
        name: dataTable
        config:
          tableName: ${self:custom.tableName.data}
          serviceRoleArn: !GetAtt AppSyncDynamoDBServiceRole.Arn

      - type: AWS_LAMBDA
        name: bulkDataSource
        config:
          lambdaFunctionArn: "arn:aws:lambda:${self:provider.region}:${aws:accountId}:function:${self:service}-${self:provider.stage}-bulkDataHandler"
          serviceRoleArn: !GetAtt AppSyncLambdaServiceRole.Arn

functions:
  dataToS3:
    name: ${self:service}-${self:provider.stage}-dataToS3
    handler: src/functions/data_handlers/data_to_s3.handler
    layers:
      - { Ref: DependenciesLambdaLayer }  # Reference the layer
    events:
      - stream:
          type: dynamodb
          arn: !GetAtt DataTable.StreamArn
    environment:
      DATA_BUCKET: !Ref DataBucket
      WORKSPACE_TABLE: ${self:custom.tableName.workspace}
      PATH_TABLE: ${self:custom.tableName.path}
      COMPONENT_TABLE: ${self:custom.tableName.component}
      DATA_TABLE: ${self:custom.tableName.data}

  cascadeDelete:
    name: ${self:service}-${self:provider.stage}-cascadeDelete
    handler: src/functions/cascade_handlers/cascade_delete.handler
    layers:
      - { Ref: DependenciesLambdaLayer }  # Reference the layer
    events:
      - stream:
          type: dynamodb
          arn: !GetAtt WorkspaceTable.StreamArn
    environment:
      WORKSPACE_TABLE: ${self:custom.tableName.workspace}
      PATH_TABLE: ${self:custom.tableName.path}
      COMPONENT_TABLE: ${self:custom.tableName.component}
      DATA_TABLE: ${self:custom.tableName.data}

  bulkDataHandler:
    name: ${self:service}-${self:provider.stage}-bulkDataHandler
    handler: src/functions/data_handlers/bulk_data_handler.handler
    layers:
      - { Ref: DependenciesLambdaLayer }  # Reference the layer
    environment:
      WORKSPACE_TABLE: ${self:custom.tableName.workspace}
      PATH_TABLE: ${self:custom.tableName.path}
      COMPONENT_TABLE: ${self:custom.tableName.component}
      DATA_TABLE: ${self:custom.tableName.data}
      ACCOUNT_TABLE: ${self:custom.tableName.account}

package:
  patterns:
    - '!**/*.test.js'
    - '!**/*.pyc'
    - '!.pytest_cache/**'
    - '!__pycache__/**'
    - '!node_modules/**'
    - '!tests/**'
    - '!.coverage'
    - '!.pytest_cache'
    - '!.git/**'

resources:
  Resources:
    # AppSync IAM Roles
    AppSyncDynamoDBServiceRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: appsync.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: DynamoDBAccess
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:GetItem
                    - dynamodb:PutItem
                    - dynamodb:UpdateItem
                    - dynamodb:DeleteItem
                    - dynamodb:Query
                    - dynamodb:Scan
                  Resource:
                    - !GetAtt UserTable.Arn
                    - !GetAtt AccountTable.Arn
                    - !GetAtt WorkspaceTable.Arn
                    - !GetAtt PathTable.Arn
                    - !GetAtt ComponentTable.Arn
                    - !GetAtt DataTable.Arn
                    - !Sub "${UserTable.Arn}/index/*"
                    - !Sub "${AccountTable.Arn}/index/*"
                    - !Sub "${WorkspaceTable.Arn}/index/*"
                    - !Sub "${PathTable.Arn}/index/*"
                    - !Sub "${ComponentTable.Arn}/index/*"
                    - !Sub "${DataTable.Arn}/index/*"

    AppSyncLambdaServiceRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: appsync.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: LambdaInvoke
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - lambda:InvokeFunction
                  Resource:
                    - "arn:aws:lambda:${self:provider.region}:${aws:accountId}:function:${self:service}-${self:provider.stage}-bulkDataHandler"

    # DynamoDB Tables
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName.user}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    AccountTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName.account}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    WorkspaceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName.workspace}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

    PathTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName.path}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    ComponentTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName.component}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    DataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName.data}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

    # S3 Bucket
    DataBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${self:provider.stage}-data-bucket